namespace SpriteKind {
    export const tinyfish = SpriteKind.create()
    export const fishy = SpriteKind.create()
    export const cap = SpriteKind.create()
    export const apa = SpriteKind.create()
}
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile1`, function (sprite, location) {
    game.gameOver(true)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile2`, function (sprite, location) {
    game.gameOver(false)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.fishy, function (sprite, otherSprite) {
    sprites.destroy(otherSprite)
    big_fish = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Enemy)
    animation.runImageAnimation(
    big_fish,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . f f f f f f f f . . . . . . . 
        f f 2 2 2 2 2 2 f f f . . . . . 
        f 7 2 2 2 2 2 2 2 2 f f . . . . 
        f 7 a 2 2 2 2 2 2 2 2 f f . . . 
        7 7 2 2 2 2 2 2 2 2 2 2 f f . . 
        f f f f f f f 2 2 2 2 2 2 f f . 
        . . . . . . . f f f 2 2 2 2 f . 
        . . . . . . . . . f f 2 2 2 f f 
        . . . . . . . . . . f f 2 2 2 f 
        . . . . . . . . . . . f f 2 2 f 
        . . . . . . . . . f f 2 2 2 2 f 
        . . . . . . f f f f f f f f f f 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . f f f f f f f f . . . . . . . 
        f f 2 2 2 2 2 2 f f f . . . . . 
        f 7 2 2 2 2 2 2 2 2 f f . . . . 
        f 7 a 2 2 2 2 2 2 2 2 f f . . . 
        7 7 2 2 2 2 2 2 2 2 2 . . . . . 
        f f f f f f f 2 2 2 2 . . . 9 9 
        . . . . . . . f f f 2 . . . . 9 
        . . . . . . . . . f . . 8 8 . 9 
        . . . . . . . . . . 9 . 8 8 8 9 
        . . . . . . . . . . 9 8 8 8 8 . 
        . . . . . . . . . . 9 . 8 8 8 8 
        . . . . . . . . . 9 9 9 8 9 8 8 
        `],
    100,
    true
    )
    big_fish.setPosition(vop.x + 80, vop.y - 80)
    big_fish.follow(vop)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprites.destroy(otherSprite)
    if (vop.y < otherSprite.y) {
        info.changeScoreBy(5)
    } else {
        info.changeLifeBy(-1)
    }
})
let big_fish: Sprite = null
let fishy: Sprite = null
let vop: Sprite = null
scene.setBackgroundColor(8)
vop = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . f . . . . . 
    . . . . f f f f f f 4 f . . . . 
    . . . f 4 4 4 4 4 4 4 f . . . . 
    . . . f 6 4 4 4 4 4 4 f . . . . 
    . . . f 4 4 4 4 4 4 4 4 f . . . 
    . . . f 4 4 4 4 4 4 4 f f . . . 
    . . . . f f f f f 4 4 f . . . . 
    . . . . . . . . . . f f . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(vop, 100, 100)
scene.cameraFollowSprite(vop)
tiles.setCurrentTilemap(tilemap`level2`)
scene.setBackgroundImage(img`
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ..................................................eeeee.........................................................................................................
    ..................................................eeeee.........................................................................................................
    ..................................................eeeeee........................................................................................................
    ..............................................eeeeeeeeee........................................................................................................
    ..............................................eeeeeeeeee............................................................................eeeee.......................
    ..............................................eeeeeeeeee............................................................................eeeee.......................
    ..............................................eeeeeeeeee.........................................................................eeeeeeeee......................
    .............................................eeeeeeeeeee........................................................................eeeeeeeeee......................
    .............................................eeeeeeeeeee.......................................................................eeeeeeeeeeee.....................
    ............................................eeeeeeeeeeee......................................................................eeeeeeeeeeeee.....................
    ............................................eeeeeeeeeeee.....................................................................eeeeeeeeeeeeeee....................
    ...........................................eeeeeeeeeeeeee...................................................................eeeeeeeeeeeeeeee....................
    ...........................................eeeeeeeeeeeeee..................................................................eeeeeeeeeeeeeeeee....................
    ...........................................eeeeeeeeeeeeeee................................................................eeeeeeeeeeeeeeeeee....................
    ...........................................eeeeeeeeeeeeeee...............................................................eeeeeeeeeeeeeeeeeeee...................
    ...........................................eeeeeeeeeeeeeeee.............................................................eeeeeeeeeeeeeeeeeeeeee..................
    ...........................................eeeeeeeeeeeeeeee............................................................eeeeeeeeeeeeeeeeeeeeeee..................
    ...........................................eeeeeeeeeeeeeeeee..........................................................eeeeeeeeeeeeeeeeeeeeeeee..................
    ..........................................eeeeeeeeeeeeeeeeee.........................................................eeeeeeeeeeeeeeeeeeeeeeeee..................
    ..........................................eeeeeeeeeeeeeeeeee........................................................eeeeeeeeeeeeeeeeeeeeeeeeeee.................
    ..........................................eeeeeeeeeeeeeeeeee......................................................eeeeeeeeeeeeeeeeeeeeeeeeeeeee.................
    .........................................eeeeeeeeeeeeeeeeeeee....................................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeee.................
    .........................................eeeeeeeeeeeeeeeeeeee...................................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.................
    .........................................eeeeeeeeeeeeeeeeeeee..................................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    .........................................eeeeeeeeeeeeeeeeeeeee...............................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    .........................................eeeeeeeeeeeeeeeeeeeee..............................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    ........................................eeeeeeeeeeeeeeeeeeeeeee............................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    ........................................eeeeeeeeeeeeeeeeeeeeeee...........................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    ........................................eeeeeeeeeeeeeeeeeeeeeee..........................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    ........................................eeeeeeeeeeeeeeeeeeeeeeee........................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    ........................................eeeeeeeeeeeeeeeeeeeeeeee.......................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    ........................................eeeeeeeeeeeeeeeeeeeeeeee.......................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    ........................................eeeeeeeeeeeeeeeeeeeeeeee......................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    ........................................eeeeeeeeeeeeeeeeeeeeeeeee....................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    .......................................eeeeeeeeeeeeeeeeeeeeeeeeee...................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    .......................................eeeeeeeeeeeeeeeeeeeeeeeeeee................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    .......................................eeeeeeeeeeeeeeeeeeeeeeeeeeee..............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    .......................................eeeeeeeeeeeeeeeeeeeeeeeeeeee.............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    .......................................eeeeeeeeeeeeeeeeeeeeeeeeeeee............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    .......................................eeeeeeeeeeeeeeeeeeeeeeeeeeeee..........................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    ......................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeee.........................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................
    ......................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeee.........................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.................
    .....................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.......................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.................
    ....................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.................
    ....................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..................
    ...................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..................
    ...................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...................
    ..................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...................
    ..................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...................
    ..................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...................
    .................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee....................
    .................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee....................
    ................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee....................
    ................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.....................
    ................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.....................
    ................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.....................
    ................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.....................
    ...............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......................
    ...............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......................
    ...............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......................
    ...............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.......................
    ..............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.......................
    ..............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee........................
    ..............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee........................
    ..............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.........................
    ..............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.........................
    .............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..........................
    .............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..........................
    .............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........................
    ............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........................
    ............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee............................
    ............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee............................
    ............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee............................
    ............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee............................
    ............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............................
    ............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............................
    ............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..............................
    ............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...............................
    ...........................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...............................
    ...........................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................................
    ...........................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................................
    ..........................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.................................
    ..........................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.................................
    ..........................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..................................
    ..........................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...................................
    ..........................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...................................
    ..........................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee....................................
    ..........................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.....................................
    ..........................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.....................................
    ..........................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......................................
    ..........................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.......................................
    ...........................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.......................................
    ...........................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee........................................
    ...........................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..........................................
    .............................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........................................
    ..................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee............................................
    .......................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.............................................
    ........................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...............................................
    .........................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................................................
    ..........................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.................................................
    ...........................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee....................................................
    ............................................eeeeeeeeeeeeeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......................................................
    .............................................eeeeeeeeeeeeeeeeeeeeeeee.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee........................................................
    ...............................................eeeeeeeeeeeeeeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeeeeeee............................................................
    .................................................eeeeeeeeeeeeeeeeeee.......eeeeeeeeeeeeeeeeeeeeeee..............................................................
    `)
scene.cameraFollowSprite(vop)
info.setLife(5)
for (let value of tiles.getTilesByType(assets.tile`myTile0`)) {
    fishy = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . 8 8 . . . . . . . . . 
        . 8 8 8 8 8 8 8 8 8 8 8 8 8 . . 
        8 8 9 9 9 9 9 9 9 9 9 9 9 9 8 . 
        8 9 d 9 9 9 9 9 9 9 9 9 9 9 8 8 
        8 8 9 9 9 9 9 9 9 9 9 9 9 9 8 . 
        . 8 8 9 9 9 9 9 9 9 9 9 9 9 8 . 
        . . 8 8 8 9 9 9 9 9 9 9 9 8 . . 
        . . . . 8 8 8 8 9 9 9 9 8 8 . . 
        . . . . . . . . 8 8 8 8 8 . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.fishy)
    tiles.placeOnTile(fishy, value)
    tiles.setTileAt(value, assets.tile`transparency16`)
}
